### PR TITLE
Added support for wp_site_icon (since WP 4.3)

### PR DESCRIPTION
**Pull request by JoryHogeveen**
Added support for the new WP Site Icon (added since WP 4.3) in the favicon selections.

When a user has added a custom site icon this icon will override the stylesheet icons and the hook in get_favicon_path.

Why also the hook? My thought was that since user actually used this it's safe to say he/she want's to use this icon instead of the theme icon. Feedback welcome!

### CODE REVIEW

**Comment by JoryHogeveen** [comment]
Again, can't figure out why my pull request also contains the "merge/pullrequest" from your master..

Can somebody please explain how I can make a pull request with JUST the changes I've made? Not my update from the Bueltge master?

**Comment by bueltge** [comment]
Hi Jory. Thanks again.
If you use my last master branch, then should only your changes inside the pull request. But I have send small changes on yesterday and maybe you haven't this inside your repository.

Fine request, was a issues on my list #13 

Have you also tested this with the custom hooks, that this also works? Lot of people use this hook for custom favicon. - https://github.com/bueltge/WordPress-Multisite-Enhancements/wiki/Filter-Hook-for-Favicon-File-Path

**Comment by JoryHogeveen** [comment]
Hi Frank,

I think i merge the wrong way. What is do is create a pull request for myself to get your current master branch. Is that correct?

Also on your not of the custom hooks. When a user had added a favicon with the new WP functionality this will override alle theme and hook icons.
My thought on the was since the favicon is manually uploaded this way a user would likely want to see this icon instead of any other, agree?

The hook is mostly used for custom themes that add favicon a different way, so that won't be needed anymore when using the WP way since 4.3.
An option would be to add a "mandatory" boolean that will override the WP default icon.

Let me know!

**Comment by bueltge** [comment]
Hi Jory,
master branch is possible. Better is a new branch to the topic, issue - see https://github.com/bueltge/wordpress-multisite-enhancements/blob/master/CONTRIBUTING.md
After a review I merge the branches. It is much easier for me to work on master and review new features, changes.

For the pull request, do you have see this helping page - https://help.github.com/articles/creating-a-pull-request/ ?

To the favicon feature. I think is ok, currently. We will see the feedback from users.
Thanks a lot again for your help.

**Comment by bueltge** [comment]
Fixed #13

**Pull request merged**
