### PR TITLE
init class Multisite_Add_Ssh_Identifier like the others. Easier unhoo…

### LINKED ISSUE #35: different init for SSL identifier class
Is there any explanation why the `class Multisite_Add_Ssh_Identifier` is init different from the other classes?
https://github.com/bueltge/wordpress-multisite-enhancements/blob/master/inc/autoload/class-add-ssl-identifier.php#L10-L14

### PR DESCRIPTION
**Pull request by cfoellmann**
Easier unhooking ;-)
Closes #35

### CODE REVIEW

**Comment by bueltge** [comment]
@cfoellmann I think is not the best idea to get back to singletons. If we will add tests for each function, class then is an singleton not helpful. We should get an solution, that supports unit test, not static singletons.

**Comment by cfoellmann** [comment]
OK. Sure.
Would it be better for me to simply "remove" the anonymous function? Unhooking is easier when you do not use them in add_action() stuff

**Comment by bueltge** [comment]
Yes, the anonymous function is not helpful for the chance to unhook. :heart:

**Comment by bueltge** [comment]
@cfoellmann My small commit 783c8fc should helps you? Feel free to close the PR and issues, if is done.

**Pull request closed without merging**
